schema_version: 1

context:
  name: rstream
  version: "1.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/rstream-${{ version }}.tar.gz
  sha256: ab9bbfe630b871fedf5261309073f4fccda48205ee73e3989a372d392a9d3132

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - requests >=2.31.0,<3.0.0
    - mmh3 >=5.2.0,<6.0.0
    - typing_extensions >=4.11.0,<5.0.0

tests:
  - python:
      imports:
        - rstream
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: A python client for RabbitMQ Streams
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/rabbitmq-community/rstream

extra:
  recipe-maintainers:
    - akrherz
